# Generated by Django 5.0 on 2023-12-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="quick_description",
            field=models.TextField(default="quick description"),
        ),
    ]
